version: "3"
services:
  web:
    image: nginx:latest
    container_name: my-laravel-app
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - app
    networks:
      - my_network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my-laravel-app-app
    volumes:
      - ./src:/var/www/html
    networks:
      - my_network

networks:
  my_network:
